#!/bin/bash

# Update Git submodules
pip install flask flask_cors bs4 lxml pelican markdown gevent
# pyInstall Python packages using pippip install flask flask_cors bs4 lxml pelican markdown gevent


# Optionally, you can add more commands or customizations here.
