#!/bin/bash

# Update Git submodules
git submodule update --init
pip install flask flask_cors bs4 lxml pelican markdown gevent
# pyInstall Python packages using pip


# Optionally, you can add more commands or customizations here.
